import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service',
}

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-16">
      <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
      <p className="text-gray-400 text-sm mb-10">Last updated: January 2025</p>

      <div className="space-y-8 text-sm text-gray-700 leading-relaxed">
        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">1. Acceptance of Terms</h2>
          <p>
            By accessing or using ProposalKit, you agree to be bound by these Terms of Service. If you do not agree, do not use the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">2. Description of Service</h2>
          <p>
            ProposalKit is an AI-powered proposal generation tool for agencies and freelancers. We provide tools to create, edit, and export professional business proposals.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">3. User Responsibilities</h2>
          <p>
            You are responsible for the accuracy of information you enter and the content of proposals you send to clients. ProposalKit provides AI-generated drafts — always review proposals before sending. You agree not to use ProposalKit for any unlawful purpose.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">4. AI-Generated Content</h2>
          <p>
            Proposals generated by AI are provided as drafts. ProposalKit makes no warranty that AI-generated content is accurate, complete, or suitable for your specific use case. You retain full responsibility for reviewing and editing proposals before use.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">5. Intellectual Property</h2>
          <p>
            You own the proposals you create using ProposalKit. ProposalKit retains ownership of the platform, AI models, and templates.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">6. Limitation of Liability</h2>
          <p>
            ProposalKit is provided "as is". We are not liable for any indirect, incidental, or consequential damages arising from your use of the service, including lost business or failed proposal outcomes.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-gray-900 mb-3">7. Contact</h2>
          <p>
            Questions about these terms? Contact us at legal@proposalkit.com.
          </p>
        </section>
      </div>
    </div>
  )
}
